### ISSUE TITLE
Settings: Customize hot keys

### ISSUE THREAD

**Issue by RyKilleen** [RyKilleen/brancato#16]
Look into the underlying libraries, confirm if there's a way to lint user input or any helper libraries to capture.

**Comment by RyKilleen** [comment]
Waiting on maintainer support in [Discord](https://discord.com/channels/616186924390023171/731495028677148753/951366583563993118).

Related: https://github.com/tauri-apps/tauri/discussions/2378

**Comment by RyKilleen** [comment]
Relevant code:
- https://github.com/tauri-apps/tao/blob/dev/src/accelerator.rs#L265
- https://github.com/tauri-apps/tao/blob/dev/src/keyboard.rs#L666

Potentially useful libraries
- [react-hotkeys-hook](https://www.npmjs.com/package/react-hotkeys-hook)
- [hotkeys.js](https://wangchujiang.com/hotkeys/)

**Comment by RyKilleen** [comment]
@SeanKilleen if you could set custom bindings, what would you bind it to?

**Comment by SeanKilleen** [comment]
@RyKilleen personally I'm fine with the default as long as I know it -- but if you're going to do it I'd allow some combination of up to 3 of control / alt / shift and a key. But you could build to that and start with one of those + user's choice of key etc.
