### ISSUE TITLE
Update omnibar immediately upon save

### ISSUE THREAD

**Issue by SeanKilleen** [RyKilleen/brancato#19]
Reproduction:

* Open settings
* Add a new workflow
* Save the new workflow
* Open the Omnibar

Expected behavior: New workflow exists there
Current behavior: Workflow change isn't reflected until I restart the app

Still, this is way cool.

**Comment by RyKilleen** [comment]
Hmm, that must be a regression because I was testing that exact scenario. I'll take a look!

**Comment by RyKilleen** [comment]
I'm updating the appState but not telling the client to refresh it...

**Comment by RyKilleen** [comment]
closed by #20
