### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by RyKilleen** [RyKilleen/brancato#24]
This is something I'd use all the time.  `55 * 3`, `22 - 5` etc

**Comment by SeanKilleen** [comment]
Going after the powertoys run utility? :) https://docs.microsoft.com/en-us/windows/powertoys/run

**Comment by RyKilleen** [comment]
@SeanKilleen One part that, one part just wholly biting [Ueli](https://ueli.app/) which has been my go-to.  It looks like they use Wox Launcher underneath which is a big inspiration for Ueli

**Comment by RyKilleen** [comment]
https://crates.io/crates/meval
