### ISSUE TITLE
"Run at startup" option/setting

### ISSUE THREAD

**Issue by SeanKilleen** [RyKilleen/brancato#27]
I like that Brancato doesn't run at startup by default, but I think it'd be a great idea to allow someone to opt-in to startup behavior.

**Comment by RyKilleen** [comment]
Pretty sure this involves setting some WiX fragments manually, so going to wait for a little community feedback.

**Comment by RyKilleen** [comment]
https://crates.io/crates/auto-launch

Per Fabian: "note that what this crate does is really simple on linux & windows (mac is weird) so you can get around without it "

**Comment by RyKilleen** [comment]
https://github.com/tauri-apps/tauri/discussions/2576#discussioncomment-1433160
https://github.com/tauri-apps/tauri/issues/2589

**Comment by RyKilleen** [comment]
For reference: https://github.com/zzzgydi/clash-verge/blob/b2a24c7abd82f4650ec3ec873b742219169310de/src-tauri/src/core/verge.rs#L73

**Comment by RyKilleen** [comment]
Should be even easier now:

https://github.com/tauri-apps/tauri-plugin-autostart
