### ISSUE TITLE
Request: Set configuration file location

### ISSUE THREAD

**Issue by SeanKilleen** [RyKilleen/brancato#47]
**Is your feature request related to a problem? Please describe.**

I have to duplicate workflows across machines.

**Describe the solution you'd like**

In the Brancato settings, I'd like to also be able to set where to save the configuration/settings file itself. (this would be the only setting that lives within the Brancato installation). This way, I could point it to a location in OneDrive or DropBox, and have my machines naturrally synchronize.

**Additional context**

Note: I wouldn't need Brancato to monitor when its config file changes and update; just being able to restart and have things synchronized would be pretty nifty.

I also recognize that paths are different on different systems sometimes and I'd be willing to adapt to that myself (and I can imagine anyone using such a feature would be aware of this as well.)

**Comment by RyKilleen** [comment]
So this should be pretty straight-forward to accommodate, and a really great self-syncing solution. Definitely worth adding!

**Comment by RyKilleen** [comment]
**Changes needed:**

- Create a new `app-config.toml` at first startup, with the default `user-config` path saved
- Create a default `user-config.json`

**When a user sets a new location for the config:**

- Save the new location in an `app-config.toml`
- Move the user-config to that location
----

Additionally, listen to file changes and update user state should be straight-forward.

**Comment by RyKilleen** [comment]
Running into a frustrating permissions issue with copying files in the main thread. Working with the `tauri` community to get it sorted.

**Comment by RyKilleen** [comment]
Turns out it was me, go figure! Move files to file paths, not folder paths....

This is held up now by a challenge of updating state across threads.
