### ISSUE TITLE
Request: Tell me which version I'm using

### ISSUE THREAD

**Issue by SeanKilleen** [RyKilleen/brancato#51]
**Is your feature request related to a problem? Please describe.**

I wasn't sure if I had the latest version on my desktop and there wasn't an easy way to tell from within the app.

**Describe the solution you'd like**

Print the version number somewhere within the UI (no preference on where -- bottom of settings page, title bar, anywhere you deem best).

**Comment by RyKilleen** [comment]
Getting the version value is an unknown atm.

We can surface this in a few spots, from easiest to coolest:

1. Some native solution, like an item in the right-click menu of the system tray icon / a window menu
2. Display it in the settings window somewhere
3. When you type `version` into the omnibar

I'll aim for 1 and then shoot for 3.

I'd rather put time into the auto-updater but this should provide some easy value up front.
