### ISSUE TITLE
Bug: non-https URLs do not appear to work

### ISSUE THREAD

**Issue by SeanKilleen** [RyKilleen/brancato#52]
Reproduction steps:

* Open Brancato settings
* Create a new workflow
* Add an https URL to the workflow
* Add an http URL to the workflow
* Run the workflow

Expected behavior: Both URLs open
Actual behavior: only the https URL opens.

Tried it with one http URL only (expected behavior: opens; actual behavior: nothing happens)

Noticed this while trying to add a URL for something I commonly run at `http://localhost:[port]`

**Comment by RyKilleen** [comment]
I specifically targeted https only in the code, having not considered it for local dev.... this should be an easy fix.
