### ISSUE TITLE
Request: Open Brancato on the monitor I call it from

### ISSUE THREAD

**Issue by SeanKilleen** [RyKilleen/brancato#75]
**Is your feature request related to a problem? Please describe.**

I am using a docking station -- my setup, from left to right is: my laptop monitor, my "main" monitor, and a monitor to the right.

When I am within my main monitor (have clicked on it), I use the brancato shortcut but I don't see it because it appears on my laptop monitor to the left. The monitor I want to see it on -- the middle one -- is set as my main display in windows.

**Describe the solution you'd like**

When I use the Brancato shortcut, I'd like it to appear either 1) on the monitor I was last active on or 2) on the monitor designated as my main monitor.

**Additional context**

Brancato starts when my laptop starts up, at which point those other monitors are not yet available as I typically haven't activated the docking station. So it's possible that Brancato _is_ looking for my main monitor, isn't re-checking later.

____

This isn't critical, but it is very interesting so I thought you'd want me to add it.

**Comment by SeanKilleen** [comment]
Update -- I restarted Brancato and sure enough, it appears on my main monitor.

So it seems the true "fix" in this case would be to check prior to showing the omnibox to see whether the main monitor has changed.

**Comment by RyKilleen** [comment]
This is very interesting and I'm excited to renew interest in this, glad you use it enough to raise it!
