### ISSUE TITLE
Browser tabs opening sync instead of in parallel?

### ISSUE THREAD

**Issue by RyKilleen** [RyKilleen/brancato#78]
@SeanKilleen reported this and I've seen it in the past. This might be dependent on an underlying lib issue, will investigate!

**Comment by SeanKilleen** [comment]
@RyKilleen Looks like this is still happening with 0.9.4. It's possible it might not be released yet though. I might be too impatient for 0.10.0 :) 

![2022-07-09_Brancato_ParallelTabIssueDemonstration](https://user-images.githubusercontent.com/2148318/178126764-9f818867-460c-4e90-9f6a-4c8034b7f153.gif)

**Comment by SeanKilleen** [comment]
Nevermind; I see it's not yet released. 👍

**Comment by RyKilleen** [comment]
One more reason to setup auto release 😜
