### ISSUE TITLE
MacOS Build no longer working

### ISSUE THREAD

**Issue by SeanKilleen** [RyKilleen/brancato#80]
Documenting the journey here.

Error: 

> Error failed to bundle project: failed to upload app to Apple's notarization servers.: failed to upload app to Apple's notarization servers.: `failed to run xcrun`

**Comment by SeanKilleen** [comment]
So the issue doesn't seem to be a change in OS version itself. `macos-latest` as a runner has used OS 11 since Sep 2021: https://github.blog/changelog/2021-09-29-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-big-sur-11/

And our builds have been working as of April. 

So, next step -- I'll look to see tooling changes since our last successful build.

**Comment by SeanKilleen** [comment]
FYI, the search I'm using: `is:pr is:closed created:>2022-04-02 "macOS 11" `

https://github.com/actions/virtual-environments/pulls?q=is%3Apr+is%3Aclosed+created%3A%3E2022-04-02+%22macOS+11%22

**Comment by SeanKilleen** [comment]
OK, so likely one of these:

* https://github.com/actions/virtual-environments/pull/5337
* https://github.com/actions/virtual-environments/pull/5382
* https://github.com/actions/virtual-environments/pull/5395
* https://github.com/actions/virtual-environments/pull/5401

Going to check our logs a little more closely now to get momre info.

**Comment by SeanKilleen** [comment]
Also just adding that it's not the Tauri action -- That hasn't been updated since Nov 2021. https://github.com/tauri-apps/tauri-action/releases

**Comment by SeanKilleen** [comment]
OK, so I think the issue here is that the build is attempting to notarize the app, which I believe we don't intend for it to do and never set it up to do.

Unfortunately, the last successful build logs have been deleted so I can't prove that's the difference, but we explicitly call the Tauri GitHub action without the environment variables that are required in order to notarize the app. So I think in this case, the issue might be that notarization is attempted at all.

**Comment by SeanKilleen** [comment]
I wrote this up for the Tauri team in the hope that they might have some more insight: https://github.com/tauri-apps/tauri-action/issues/291

It does seem to me like the tooling is attempting to notarize the app which would definitely fail because we are not providing the right environment variables for that (which I think in the past allowed it to be skipped.)

**Comment by RyKilleen** [comment]
I have a feeling this is an issue between us and Apple, this is likely how our app was always signed. I don't have the creds but I'm seeing similar issues in other repos like here:  [failed to upload app to Apple's notarization servers](https://github.com/electron/electron-notarize/issues/24)

Looks like signing in and accepting a new TOS agreement solves the issue...

**Comment by SeanKilleen** [comment]
Wow, yep, that was it. I was thrown off because I knew we had not added certain env variables related to notarization. But I guess it gets notarized in some way anyway.

Good catch, @RyKilleen! I accepted the new agreement and we're back up and running.

**Comment by iamfaiz123** [comment]
we're getting the same error
 
Notarizing /Users/runner/work/brancato/brancato/src-tauri/target/release/bundle/macos/brancato.app
       Error failed to bundle project: failed to upload app to Apple's notarization servers.: failed to upload app to Apple's notarization servers.: `failed to run xcrun`

this muts sound stupid, but in my apple developers account where can i accept a new POS?

**Comment by SeanKilleen** [comment]
@iamfaiz123 not a stupid question at all. I had to figure it out for myself. I believe I signed into the Apple Dev account that we use for signing things, at which point a "new TOS" appeared and I had to accept it. My memory is pretty hazy so I can't guarantee that's it, but I wish you good luck in finding it! If it happens again I'll write a blog post about it. :)

**Comment by RyKilleen** [comment]
@iamfaiz123 this particular issue https://github.com/electron/notarize/issues/24 has a lot of useful context, seemingly related solutions that originally triggered the realization:



Could be anything from copyright image / video usage, to having to sign into the developer account at https://appstoreconnect.apple.com 

Best of luck!
