### ISSUE TITLE
Fix dependabot builds

### ISSUE THREAD

**Issue by RyKilleen** [RyKilleen/brancato#86]
Looks like dependabot no longer has access to secrets.

https://github.blog/changelog/2021-12-09-github-actions-changes-to-permissions-in-workflows-triggered-by-dependabot/

**Comment by SeanKilleen** [comment]
Huh, that's weird. Sorry, I completely forgot about this. Dependabot has never used its own secrets previously; maybe GitHub changed something there. It runs a GitHub action so should use the same as all the other actions.

**Comment by SeanKilleen** [comment]
Yep, looks like I just need to duplicate the secret values in an additional section in settings. Makes sense from a security perspective. I'll knock this out today when I'm home.

**Comment by RyKilleen** [comment]
Wonder if it makes sense to move our company certs to org level secrets as well?

**Comment by SeanKilleen** [comment]
FWIW I also submitted a feature request to GitHub to copy secrets into Dependabot or Org levels: https://github.community/t/feature-suggestion-copy-secrets-to-dependabot-secrets-or-org-secrets/263725

**Comment by SeanKilleen** [comment]
@RyKilleen I'm now seeing Dependabot builds running with secrets usage as expected. Going to consider this resolved. 👍

**Comment by RyKilleen** [comment]
Awesome, thanks for tackling that!
