### ISSUE TITLE
Feature: Accept variables from search in template strings

### ISSUE THREAD

**Issue by RyKilleen** [RyKilleen/brancato#90]
**Is your feature request related to a problem? Please describe.**
I would love to build out a workflow that accepts a variable and can use it in a template string in one or more steps. We already do this to some degree with the different search engine options.

**Describe the solution you'd like**
In the omni bar, if I select a workflow that can accept parameters, I can pass comma-separated strings to athat workflow. 

In defining workflows, I can accept multiple parameter in a step like so

**Web**
`https://some-website.com/${1}/${2}`

**Comment by SeanKilleen** [comment]
Oooooh nice!
